name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet: [ '9.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          cache: true

      - name: Restore
        run: dotnet restore Hoho.sln --nologo

      - name: Build (Release)
        run: dotnet build Hoho.sln -c Release --no-restore --nologo

      - name: Test
        if: ${{ hashFiles('**/*Tests.csproj') != '' }}
        run: dotnet test Hoho.sln -c Release --no-build --nologo --verbosity normal

